---
- name: Установка и настройка Nginx
  hosts: all
  become: yes  # Для выполнения команд с правами root
  tasks:
    - name: Обновить список пакетов (для Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Установить Nginx (для Debian/Ubuntu)
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Установить EPEL-репозиторий (для CentOS/RHEL)
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"

    - name: Установить Nginx (для CentOS/RHEL)
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Включить Nginx в автозагрузку
      ansible.builtin.service:
        name: nginx
        enabled: yes

    - name: Убедиться, что Nginx запущен
      ansible.builtin.service:
        name: nginx
        state: started
